# Cf. https://github.com/kubernetes/dashboard/wiki/Creating-sample-user

# Create service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kube-system

---

# Roles should slready exist
# kubectl --kubeconfig kube_config_cluster.yml -n kube-system get clusterroles

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kube-system

---

# After that, confirm with
# kubectl --kubeconfig kube_config_cluster.yml -n kube-system get serviceaccounts -o wide

# And get the token with
# kubectl --kubeconfig kube_config_cluster.yml -n kube-system describe secret $(kubectl --kubeconfig kube_config_cluster.yml -n kube-system get secret | grep admin-user | awk '{print $1}')